"""add condition_investigations table

Revision ID: 179b55d4741a
Revises: a63bcbcd6882
Create Date: 2026-04-11 17:27:12.422494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179b55d4741a'
down_revision: Union[str, Sequence[str], None] = 'a63bcbcd6882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition_investigations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('investigation_text', sa.Text(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('condition_investigations')
    # ### end Alembic commands ###
