import { Link } from "react-router-dom";
import { api } from "../api/client";
import { useFetch } from "../useFetch";
import { PageContainer, Spinner } from "../components/ui";

const GITHUB_URL = "https://github.com/hemjay07/clinicalguard";

function Stat({ value, label }: { value: number | string; label: string }) {
  return (
    <div className="rounded-lg border border-slate-200 bg-white p-5 text-center shadow-sm">
      <div className="text-3xl font-bold text-brand-700">{value}</div>
      <div className="mt-1 text-sm text-slate-500">{label}</div>
    </div>
  );
}

export function Home() {
  const conditions = useFetch(() => api.listConditions(), []);
  const safety = useFetch(() => api.safetyRules(), []);
  const cases = useFetch(() => api.listEvalCases(), []);

  return (
    <PageContainer>
      <section className="mb-8">
        <h1 className="text-3xl font-bold text-slate-800">ClinicalGuard</h1>
        <p className="mt-3 max-w-3xl text-slate-600">
          ClinicalGuard is an open-source framework for evaluating clinical AI against
          structured clinical guidelines. Ground truth is grounded in the Nigeria Standard
          Treatment Guidelines (NSTG) and authored by physicians — not generated by a model —
          so the benchmark can credibly measure models rather than mirror them.
        </p>
      </section>

      <section className="mb-8 rounded-lg border border-slate-200 bg-white p-5 shadow-sm">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500">
          What this tool does
        </h2>
        <p className="mt-2 text-slate-600">
          This is the Phase A authoring interface. A physician picks a condition, reviews the
          structured NSTG source material alongside the form, and authors an evaluation case by
          hand. No model proposes tiers or writes the case — the ground truth is authored
          directly from the source. The read-only views below make the framework's underlying
          work visible.
        </p>
      </section>

      <section className="mb-8 grid grid-cols-2 gap-4 sm:grid-cols-3">
        <Stat value={conditions.data ? conditions.data.length : "…"} label="NSTG conditions" />
        <Stat value={safety.data ? safety.data.length : "…"} label="Active safety rules" />
        <Stat value={cases.data ? cases.data.length : "…"} label="Submitted eval cases" />
      </section>

      {(conditions.loading || safety.loading || cases.loading) && <Spinner />}

      <section className="mb-10 flex flex-wrap gap-3">
        <Link to="/author" className="rounded-md bg-brand-600 px-4 py-2 font-medium text-white hover:bg-brand-700">
          Author a case
        </Link>
        <Link to="/conditions" className="rounded-md border border-slate-300 px-4 py-2 font-medium text-slate-700 hover:bg-slate-100">
          Browse conditions
        </Link>
        <Link to="/cases" className="rounded-md border border-slate-300 px-4 py-2 font-medium text-slate-700 hover:bg-slate-100">
          View submitted cases
        </Link>
      </section>

      <footer className="border-t border-slate-200 pt-6 text-sm text-slate-500">
        <div className="flex flex-wrap gap-4">
          <a href={GITHUB_URL} target="_blank" rel="noreferrer" className="hover:text-brand-700">
            GitHub repository ↗
          </a>
          <a href={`${GITHUB_URL}/blob/main/docs/methodology.md`} target="_blank" rel="noreferrer" className="hover:text-brand-700">
            Methodology ↗
          </a>
          <a href="mailto:irfanjimoh123@gmail.com" className="hover:text-brand-700">
            Contact the author
          </a>
        </div>
      </footer>
    </PageContainer>
  );
}
